CREATE TABLE customer_conversation (
  id VARCHAR(36) PRIMARY KEY,
  user_id BIGINT NULL,
  guest_hash CHAR(64) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_customer_conversation_user ON customer_conversation(user_id, created_at);

CREATE TABLE customer_message (
  id VARCHAR(36) PRIMARY KEY,
  conversation_id VARCHAR(36) NOT NULL,
  role VARCHAR(16) NOT NULL,
  content CLOB NOT NULL,
  idempotency_key VARCHAR(80) NULL,
  run_id VARCHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_customer_message_idempotency UNIQUE (conversation_id, idempotency_key)
);
CREATE INDEX idx_customer_message_history ON customer_message(conversation_id, created_at);

CREATE TABLE customer_run (
  id VARCHAR(36) PRIMARY KEY,
  conversation_id VARCHAR(36) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL,
  sequence_no INT NOT NULL,
  event_type VARCHAR(24) NOT NULL,
  data CLOB NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_customer_event_sequence UNIQUE (run_id, sequence_no)
);
CREATE INDEX idx_customer_event_run ON customer_event(run_id, id);

CREATE TABLE customer_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_key VARCHAR(64) NOT NULL,
  version INT NOT NULL,
  status VARCHAR(16) NOT NULL,
  effective_from TIMESTAMP(6) NOT NULL,
  title VARCHAR(200) NOT NULL,
  category VARCHAR(24) NOT NULL,
  excerpt CLOB NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_customer_policy_version UNIQUE (policy_key, version)
);
CREATE INDEX idx_customer_policy_effective ON customer_policy(status, effective_from, category);

CREATE TABLE customer_ticket (
  id VARCHAR(36) PRIMARY KEY,
  conversation_id VARCHAR(36) NOT NULL,
  user_id BIGINT NULL,
  order_id BIGINT NULL,
  status VARCHAR(20) NOT NULL,
  reason VARCHAR(500) NOT NULL,
  summary VARCHAR(1000) NOT NULL,
  idempotency_key VARCHAR(80) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_customer_ticket_idempotency UNIQUE (conversation_id, idempotency_key)
);
CREATE INDEX idx_customer_ticket_conversation ON customer_ticket(conversation_id, created_at);
